<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2r1x1r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2r1x1r/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE2r1x1r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE2r1x1r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE2r1x1r\appProdProjectContainer([
    'container.build_hash' => 'E2r1x1r',
    'container.build_id' => 'a648951c',
    'container.build_time' => 1654702259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2r1x1r');
